### ISSUE TITLE
stream analytics job with iot hub data 

### ISSUE THREAD

**Issue by gcogco10** [Microsoft-USEduAzure/workshops#4]
Hi Team

I need some small help based on my below logic, i can able to get data from two sensors namely; temperature, illuminance, but the field date i cant get any timestamp. I have used stream analytic job using power bi to filter these data as output.

SELECT  
    illuminance as illuminance,
    temperature as temperature,
    MAX(CAST([timeStamp] AS datetime)) AS Date
INTO 
   [PowerBIVisualizationOutput] 
FROM 
   [PowerBIVisualizationInput]
   
GROUP BY 
illuminance,
temperature,
TumblingWindow(minute,5) 

The date field is empty, is there a way around this logic or where can i improved my logic on sql query above?

![image](https://user-images.githubusercontent.com/54668501/66824790-445b5c80-ef49-11e9-8a8d-69869922f10e.png)

**Comment by spontello** [comment]
Close
